"""init schema

Revision ID: 2f192215f5ee
Revises: 
Create Date: 2026-09-14 20:47:44.377830

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f192215f5ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('yahoo_account_label', sa.String(length=255), nullable=False),
    sa.Column('playwright_profile_ref', sa.String(length=255), nullable=False),
    sa.Column('budget_limit_jpy', sa.Integer(), nullable=False),
    sa.Column('is_session_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_table('pairing_codes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('auction_positions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('auction_id', sa.String(length=255), nullable=False),
    sa.Column('auction_status', sa.String(length=32), nullable=False),
    sa.Column('max_bid_accepted_jpy', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'auction_id', name='uq_auction_positions_account_auction')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.create_table('previews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('auction_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('listing_snapshot', sa.JSON(), nullable=False),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previews_auction_id'), 'previews', ['auction_id'], unique=False)
    op.create_index(op.f('ix_previews_owner_id'), 'previews', ['owner_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('auction_id', sa.String(length=255), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('preview_id', sa.String(length=64), nullable=False),
    sa.Column('command_status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('auction_status', sa.String(length=32), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('unknown_cost_policy', sa.String(length=16), nullable=False),
    sa.Column('supersedes_command_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by_worker', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['preview_id'], ['previews.id'], ),
    sa.ForeignKeyConstraint(['supersedes_command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_commands_owner_idem_key'),
    sa.UniqueConstraint('owner_id', 'intent_id', name='uq_commands_owner_intent_id')
    )
    op.create_index(op.f('ix_commands_auction_id'), 'commands', ['auction_id'], unique=False)
    op.create_index(op.f('ix_commands_owner_id'), 'commands', ['owner_id'], unique=False)
    op.create_table('budget_reservations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('reserved_jpy', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('trade_ref', sa.String(length=255), nullable=True),
    sa.Column('amount_jpy', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_results')
    op.drop_table('command_events')
    op.drop_table('budget_reservations')
    op.drop_index(op.f('ix_commands_owner_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_auction_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_previews_owner_id'), table_name='previews')
    op.drop_index(op.f('ix_previews_auction_id'), table_name='previews')
    op.drop_table('previews')
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('auction_positions')
    op.drop_table('worker_heartbeats')
    op.drop_table('pairing_codes')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
